FROM tensorflow/serving:2.12.1

COPY ./models/mobilenet_v2 /models/mobilenet_v2/1/

EXPOSE 8500

CMD ["--port=8500","--model_name=mobilenet_v2","--model_base_path=/models/mobilenet_v2","--grpc_channel_arguments=grpc.max_send_message_length=50*1024*1024", "--grpc_channel_arguments=grpc.max_receive_length=50*1024*1024", "--grpc_max_threads=1000"]

