FROM tensorflow/serving:2.11.1

COPY ./models/mobilenet_v2 /models/mobilenet_v2/1/

EXPOSE 8501

CMD ["--rest_api_port=8501","--model_name=mobilenet_v2","--model_base_path=/models/mobilenet_v2","--rest_api_num_threads=1000"]

