FROM tensorflow/serving

COPY ./models/inception_v3 /models/inception_v3/1/

EXPOSE 8500

CMD ["--rest_api_port=8500","--model_name=inception_v3","--model_base_path=/models/inception_v3","--rest_api_num_threads=1000"]

