FROM tensorflow/serving

COPY ./models/bert_imdb /models/bert_imdb/1/

EXPOSE 8500

CMD ["--rest_api_port=8500","--model_name=bert_imdb","--model_base_path=/models/bert_imdb","--rest_api_num_threads=1000"]

