FROM tensorflow/serving:2.12.1

COPY ./models/yolo_v5 /models/yolo_v5/1/

EXPOSE 8500

CMD ["--port=8500","--model_name=yolo_v5","--model_base_path=/models/yolo_v5","--grpc_channel_arguments=grpc.max_send_message_length=50*1024*1024", "--grpc_channel_arguments=grpc.max_receive_length=50*1024*1024", "--grpc_max_threads=1000"]

