FROM tensorflow/serving:2.11.1

COPY ./models/yolo_v5 /models/yolo_v5/1/

EXPOSE 8501

CMD ["--rest_api_port=8501","--model_name=yolo_v5","--model_base_path=/models/yolo_v5","--rest_api_num_threads=1000"]

