FROM tensorflow/serving

COPY ./models/mobilenet_v1 /models/mobilenet_v1/1/

EXPOSE 8501

CMD ["--rest_api_port=8501","--model_name=mobilenet_v1","--model_base_path=/models/mobilenet_v1","--rest_api_num_threads=1000"]

