FROM python:3.10.11

WORKDIR /app

COPY ./build_assets/gcp_run_python_dockerfiles/requirements.grpc.monitoring.txt /app

COPY ./build_assets/gcp_run_python_dockerfiles/grpc_start.sh /app

COPY ./build_assets/gcp_run_python_dockerfiles/push_metrics.py /app

RUN pip install --no-cache-dir -r requirements.grpc.monitoring.txt

RUN chmod 755 ./grpc_start.sh