FROM tensorflow/serving

COPY ./models/distilbert_sst2 /models/distilbert_sst2/1/

EXPOSE 8500

CMD ["--port=8500","--model_name=distilbert_sst2","--model_base_path=/models/distilbert_sst2","--grpc_channel_arguments=grpc.max_send_message_length=50*1024*1024", "--grpc_channel_arguments=grpc.max_receive_length=50*1024*1024", "--grpc_max_threads=1000"]

