FROM gcp_run_python_rest_docker_base

WORKDIR /app

COPY ./models/inception_v3 /app/inception_v3

COPY ./build_assets/gcp_run_python_dockerfiles/inception_v3/rest_main.py /app

EXPOSE 8501

CMD ["uvicorn", "rest_main:app", "--port", "8501", "--host", "0.0.0.0"]

