FROM tensorflow/serving:2.12.1

COPY ./models/bert_imdb /models/bert_imdb/1/

EXPOSE 8501

CMD ["--rest_api_port=8501","--model_name=bert_imdb","--model_base_path=/models/bert_imdb","--rest_api_num_threads=1000"]

