FROM gcp_run_python_rest_docker_base

WORKDIR /app

COPY ./models/mobilenet_v1 /app/mobilenet_v1

COPY ./build_assets/gcp_run_python_dockerfiles/mobilenet_v1/rest_main.py /app

EXPOSE 8501

CMD ["uvicorn", "rest_main:app", "--port", "8501"]

