variable "region" {}
variable "model_name" {}
variable "docker_registry" {}
variable "cpu_number" {}
variable "ram_mib" {}
variable "min_instances" {}
variable "max_instances" {}
variable "noauth_policy" {}
variable "APIS" {}
variable "prefix" {}
variable "concurrency" {}
variable "project_name" {}
variable "pushgateway_address" {}