FROM gcp_run_python_rest_docker_base

WORKDIR /app

COPY ./models/yolo_v5 /app/yolo_v5

COPY ./build_assets/gcp_run_python_dockerfiles/yolo_v5/rest_main.py /app

EXPOSE 8501

CMD ["uvicorn", "rest_main:app", "--port", "8501", "--host", "0.0.0.0"]

